"""Add bank_account_id to bank_transactions

Revision ID: 0a3c1338655b
Revises: de7f43380cd7
Create Date: 2025-09-20 10:27:53.858171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3c1338655b'
down_revision = 'de7f43380cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'bank_accounts', ['bank_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    # ### end Alembic commands ###
