"""Add synced_at to BankTransaction

Revision ID: 288586b8d308
Revises: d7c728daa9bf
Create Date: 2025-09-16 13:38:23.788923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288586b8d308'
down_revision = 'd7c728daa9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('plaid_transaction_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('bank_transactions_transaction_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['plaid_transaction_id'])
        batch_op.create_foreign_key(None, 'bank_items', ['bank_item_id'], ['id'])
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('bank_transactions_transaction_id_key'), ['transaction_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('plaid_transaction_id')
        batch_op.drop_column('bank_item_id')

    # ### end Alembic commands ###
