"""Add bank_transaction_id to Transaction

Revision ID: 2929610aa034
Revises: b222715e2069
Create Date: 2025-09-15 20:28:24.755196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2929610aa034'
down_revision = 'b222715e2069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_transaction_id', sa.Integer(), nullable=True))
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'bank_transactions', ['bank_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('bank_transaction_id')

    # ### end Alembic commands ###
