"""Add InvestmentSnapshot model

Revision ID: 45fcf9815980
Revises: 883efd7e732b
Create Date: 2025-09-17 11:16:26.012426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fcf9815980'
down_revision = '883efd7e732b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('units', sa.Numeric(precision=12, scale=4), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('snapshot_date', sa.Date(), nullable=False))
        batch_op.drop_column('invested_amount')
        batch_op.drop_column('date')
        batch_op.drop_column('profit_loss')
        batch_op.drop_column('current_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profit_loss', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('invested_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('snapshot_date')
        batch_op.drop_column('price')
        batch_op.drop_column('units')
        batch_op.drop_column('value')

    # ### end Alembic commands ###
