"""Add avg_buy_price in Investment

Revision ID: 47ca85ada947
Revises: 45fcf9815980
Create Date: 2025-09-18 15:52:33.303222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ca85ada947'
down_revision = '45fcf9815980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_basis', sa.Numeric(precision=18, scale=2), nullable=False))

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_buy_price', sa.Numeric(precision=18, scale=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('avg_buy_price')

    with op.batch_alter_table('investment_snapshots', schema=None) as batch_op:
        batch_op.drop_column('cost_basis')

    # ### end Alembic commands ###
