"""create budgets table

Revision ID: 6a5ccb794add
Revises: bc12fd66f83a
Create Date: 2025-09-23 13:25:38.103360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5ccb794add'
down_revision = 'bc12fd66f83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('budgets', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('budgets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('budgets', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'budgets', 'bank_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.alter_column('budgets', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('budgets', 'updated_at')
    op.drop_column('budgets', 'end_date')
    op.drop_column('budgets', 'start_date')
    op.drop_column('budgets', 'account_id')
    # ### end Alembic commands ###
