"""Add average_price and cost_basis to investments

Revision ID: 8ea23c72f4a7
Revises: 47ca85ada947
Create Date: 2025-09-19 19:32:52.923070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea23c72f4a7'
down_revision = '47ca85ada947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost_basis', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('cost_basis')
        batch_op.drop_column('average_price')

    # ### end Alembic commands ###
