"""Add category_id to goals

Revision ID: 90be874aa387
Revises: 8f291fd11496
Create Date: 2025-09-14 15:34:58.182160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90be874aa387'
down_revision = '8f291fd11496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
