"""Add symbol to investments

Revision ID: 93c138c97353
Revises: 2b3c1bc351b6
Create Date: 2025-09-14 09:55:09.641852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c138c97353'
down_revision = '2b3c1bc351b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
