"""Add relationship to BankTransaction

Revision ID: a0a39280caa2
Revises: 0a3c1338655b
Create Date: 2025-09-21 12:07:09.589554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a39280caa2'
down_revision = '0a3c1338655b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bank_transactions_bank_account_id_fkey'), type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('bank_transactions_bank_account_id_fkey'), 'bank_accounts', ['bank_account_id'], ['id'])

    # ### end Alembic commands ###
