"""Add cursor to BankItem

Revision ID: b222715e2069
Revises: a42b041783a3
Create Date: 2025-09-15 20:17:37.440862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b222715e2069'
down_revision = 'a42b041783a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cursor', sa.String(length=255), nullable=True))
        batch_op.alter_column('institution_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('bank_items_item_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_items', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('bank_items_item_id_key'), ['item_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('institution_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('cursor')

    # ### end Alembic commands ###
