"""Add portfolio snapshots

Revision ID: b902b72f6844
Revises: b242e1fdae63
Create Date: 2025-09-14 09:40:13.188953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b902b72f6844'
down_revision = 'b242e1fdae63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
