"""init schema

Revision ID: bc12fd66f83a
Revises: a0a39280caa2
Create Date: 2025-09-21 16:13:39.991011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc12fd66f83a'
down_revision = 'a0a39280caa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('bank_account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bank_transactions', 'bank_accounts', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'bank_account_id')
    # ### end Alembic commands ###
