"""Add synced_at to InvestmentTransaction

Revision ID: d7c728daa9bf
Revises: 44a37e61aede
Create Date: 2025-09-16 11:59:51.676647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c728daa9bf'
down_revision = '44a37e61aede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('units',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.drop_column('price_per_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('units',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
