"""Add relationship to budgets table

Revision ID: ed2d2b4ecfc3
Revises: 6a5ccb794add
Create Date: 2025-09-23 15:13:59.999209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2d2b4ecfc3'
down_revision = '6a5ccb794add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
