"""create bank tables

Revision ID: aebe17b8f3f0
Revises: b08d837070f7
Create Date: 2025-10-16 14:56:21.010541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebe17b8f3f0'
down_revision: Union[str, Sequence[str], None] = 'b08d837070f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_bank_items_id'), 'bank_items', ['id'], unique=False)
    op.create_index(op.f('ix_bank_items_user_id'), 'bank_items', ['user_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank_item_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('mask', sa.String(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('iso_currency_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_item_id'], ['bank_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank_item_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pending', sa.String(), nullable=True),
    sa.Column('iso_currency_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bank_item_id'], ['bank_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('transactions', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_column('transactions', 'pending')
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'iso_currency_code')
    op.drop_column('transactions', 'merchant_name')
    op.drop_column('transactions', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('merchant_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('iso_currency_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('pending', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('transactions', 'description')
    op.drop_column('transactions', 'transaction_type')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_bank_items_user_id'), table_name='bank_items')
    op.drop_index(op.f('ix_bank_items_id'), table_name='bank_items')
    op.drop_table('bank_items')
    # ### end Alembic commands ###
